# SPDX-FileCopyrightText: 2025 FanaticPythoner
# SPDX-License-Identifier: Apache-2.0

name: build-dist
description: Build sdist + universal wheel and generate SHA256SUMS.txt
inputs:
  python_version:
    description: Python version to use
    required: false
    default: "3.12"
outputs:
  dist_dir:
    description: Path to the built distributions
    value: ${{ steps.out.outputs.dist_dir }}
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
        cache: pip
        cache-dependency-path: |
          pyproject.toml
          requirements*.txt

    - name: Build sdist + wheel
      shell: bash
      run: |
        set -euo pipefail
        python -m venv .venv
        . .venv/bin/activate
        python -m pip install --upgrade pip build twine
        python -m build --sdist --wheel
        python -m twine check dist/*
        ls -lh dist

    - name: Generate SHA256SUMS.txt
      shell: bash
      run: |
        set -euo pipefail
        cd dist
        (for f in *; do sha256sum "$f"; done) > SHA256SUMS.txt
        ls -l

    - id: out
      shell: bash
      run: |
        echo "dist_dir=dist" >> "$GITHUB_OUTPUT"
