# SPDX-FileCopyrightText: 2025 FanaticPythoner
# SPDX-License-Identifier: Apache-2.0

name: Nightly (rolling main pre-release)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: nightly-main
  cancel-in-progress: true

jobs:
  nightly:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: pack
        name: Build artifacts
        uses: ./.github/actions/build-dist
        with:
          python_version: "3.12"

      - name: Update nightly release (purge + upload)
        uses: ./.github/actions/release-assets
        with:
          release_tag: nightly
          release_name: Nightly (main)
          prerelease: "true"
          purge_existing_assets: "true"
          create_or_move_tag: "true"
          dist_dir: ${{ steps.pack.outputs.dist_dir }}
