# SPDX-FileCopyrightText: 2025 FanaticPythoner
# SPDX-License-Identifier: Apache-2.0

name: Nightly (rolling main pre-release)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write       # needed to manage releases/assets

concurrency:
  group: nightly-main
  cancel-in-progress: true

jobs:
  nightly:
    uses: ./.github/workflows/_package_release.yml
    permissions:
      contents: write   # do NOT include id-token here (never publish to PyPI)
    with:
      release_tag: nightly
      release_name: Nightly (main)
      prerelease: true
      publish_to_pypi: false
      create_or_move_tag: true
      purge_existing_assets: true
      verify_version_tag_match: false
      python_version: "3.12"
    secrets: inherit
