name: Publish Python Package to PyPI and TestPyPI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      target_pypi:
        description: 'Target PyPI instance'
        required: true
        default: 'testpypi'
        type: choice
        options:
          - testpypi
          - pypi

jobs:
  build-and-publish:
    name: Build and publish Python distributions
    runs-on: ubuntu-latest

    # Define the environment based on the trigger
    # If it's a release, target 'pypi' environment.
    # If it's a manual dispatch, target the environment specified in the input.
    environment: ${{ (github.event_name == 'release' && 'pypi') || (github.event_name == 'workflow_dispatch' && github.event.inputs.target_pypi) }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine wheel setuptools

      - name: Build package
        run: |
          python -m build

      - name: Verify built artifacts
        run: |
          twine check dist/*

      - name: Publish package to TestPyPI
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.target_pypi == 'testpypi'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Publish package to PyPI
        if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.event.inputs.target_pypi == 'pypi')
        uses: pypa/gh-action-pypi-publish@release/v1